version: '3'
services:
  app:
    container_name: app
    build: .
    ports:
      - '8081:8081'
#      - '5432:5432'
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
       - postgres_db
       - accrual_service
    networks:
      - gofermart

  accrual_service:
    container_name: accrual
    platform: linux/x86_64
    build:
      dockerfile: Dockerfile.accrual
    ports:
      - '8080:8080'
    networks:
      - gofermart

  postgres_db:
    image: postgres:latest
    container_name: db_postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - gofermart

volumes:
  api:
  database_postgres:

networks:
  gofermart:
    driver: bridge